# Out-Of-Memory Exercise

For this exercise, you're given a purely fictional, simulated dataset. The dataset represents data from a webshop and is broken into three parts:



*   **customer data**: A catalogue over registered customers in the webshop. Contains personal information about each customer which (if this was a real dataset) would be encrypted.
*   **product data**: A catalogue of products sold by the webshop. Descriptions, price and other information.
*   **sales data**: Historic sales made by customers. Contains order total, which customer placed the order, status and other information.


In this exercise, you'll be tasked with answering concrete questions about the dataset which requires you to query it efficiently. To do this, you'll need to write SQL commands using polars to query the parquet files, and you'll be tasked with comparing the speed of these queries with a SQLite-version of the dataset.

We start with downloading the dataset in Parquet format:

In [ ]:
# Download sales data
!gdown 1xWAK9ruxl9C9SHNFV09oEasnEWhLcvWZ

# Download product data
!gdown 1Xj8dL1wgNI-NpceKzSxWvs7HHSGKWAUy

# Download customer data
!gdown 1j2In8500o0yXTCXp2hBA8GRVl68UQ5ij

Downloading...
From: https://drive.google.com/uc?id=1xWAK9ruxl9C9SHNFV09oEasnEWhLcvWZ
To: /content/sales_data.parquet
100% 79.4M/79.4M [00:00<00:00, 154MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Xj8dL1wgNI-NpceKzSxWvs7HHSGKWAUy
To: /content/product_data.parquet
100% 1.24M/1.24M [00:00<00:00, 157MB/s]
Downloading...
From: https://drive.google.com/uc?id=1j2In8500o0yXTCXp2hBA8GRVl68UQ5ij
To: /content/customer_data.parquet
100% 12.6M/12.6M [00:00<00:00, 90.9MB/s]

We then install polars:

In [ ]:
!pip install polars==0.19.12

Collecting polars==0.19.12
  Downloading polars-0.19.12-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.6/27.6 MB 57.8 MB/s eta 0:00:00
Installing collected packages: polars
  Attempting uninstall: polars
    Found existing installation: polars 0.17.3
    Uninstalling polars-0.17.3:
      Successfully uninstalled polars-0.17.3
Successfully installed polars-0.19.12

To get you started, we'll create the following SQLContext in polars:


*(If you get an error running the cell below, please restart the notebook and run the cell again)*

In [ ]:
import polars as pl

# Reference dataset parts
customer_data_path = '/content/customer_data.parquet'
product_data_path = '/content/product_data.parquet'
sales_data_path = '/content/sales_data.parquet'

# Create a pl.LazyFrame to each
customer_data = pl.scan_parquet(customer_data_path)
product_data = pl.scan_parquet(product_data_path)
sales_data = pl.scan_parquet(sales_data_path)

# Combine the LazyFrames into a SQLContext
conn = pl.SQLContext(customer_data = customer_data,
                     product_data = product_data,
                     sales_data = sales_data)

Let's now print the available tables:

In [ ]:
conn.tables()

['customer_data', 'product_data', 'sales_data']

# **Exercise 1.1**

## _Use SQL to write SELECT queries that extracts the first 7 rows of each of the tables above and print the result as a cell output._
Hint: LIMIT

In [ ]:
#SOLUTION BY RASMUS

conn.execute('SELECT * from customer_data LIMIT 7').collect().to_pandas()

,name,address,building,city,postcode,country_code,iban,swift,phone,registered,customer_id
0,Patrick Daniels,9300 Hughes Centers Apt. 469,816,South Bryceshire,35597,RU,GB87VRTK85770845773644,IOEJGBP4HP3,298.624.7051,2023-10-06,0
1,Crystal Johnson,26069 Kaitlyn Keys,193,Ramosport,58846,IQ,GB15ZOEZ27897894178766,EEDFGBM7,001-954-322-6320x8297,2016-02-24,1
2,Jonathan Greene,35056 Eric Mission Apt. 198,041,Marytown,52874,LR,GB26QYZG06175514573962,SLCHGBB5,001-217-443-7714,2017-06-08,2
3,Sandra Roberts,14394 Dean Rest,46511,Pamelaburgh,33572,CN,GB88QHSH83502472330046,CQFLGB5USXG,001-639-529-0091x9048,2016-05-14,3
4,Taylor Rush,672 Carter Groves,12206,Lake William,77390,CV,GB52JGKA12443711721689,NKRVGBJN,3217198494,2018-11-25,4
5,Joseph Burns,11507 Teresa Roads,6782,Matthewsborough,21146,MA,GB77GXAA08179343555765,XPYDGBC39OE,(346)917-4874,2019-06-07,5
6,Natalie Meza,56280 White Ferry Suite 201,124,New Rebeccaland,90604,BZ,GB12DOPM34729615659995,JTBJGBN8,(726)318-9937,2021-09-08,6

In [ ]:
conn.execute('SELECT * from product_data LIMIT 7').collect().to_pandas()

,Product Name,Category,Product Specification,Shipping Weight,item_id,item_price
0,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,Shipping Weight: 10.7 pounds (View shipping ra...,10.7 pounds,0,43.758615
1,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,Product Dimensions: 14.7 x 11.1 x 10.2...,4 pounds,1,86.863963
2,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,ProductDimensions:10.3x3.4x0.8inches|ItemWeigh...,12.8 ounces,2,119.941651
3,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,ProductDimensions:3.5x6.2x13inches|ItemWeight:...,13.4 ounces,3,49.544507
4,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,ProductDimensions:1.9x8x10inches|ItemWeight:13...,13.4 ounces,4,22.285907
5,"Terra by Battat – 4 Dinosaur Toys, Medium – Di...",None,ProductDimensions:8.7x3.9x3.4inches|ItemWeight...,1.4 pounds,5,98.748196
6,Rubie's Child's Pokemon Deluxe Pikachu Costume...,"Clothing, Shoes & Jewelry | Costumes & Accesso...",ProductDimensions:16x8x1inches|ItemWeight:1pou...,9.8 ounces,6,154.408344

In [ ]:
conn.execute('SELECT * from sales_data LIMIT 7').collect().to_pandas()

,order_id,order_sub_id,status,item_id,item_price,order_date,month_id,year_id,customer_id,order_total
0,0,0,completed,8057,23.034306,2023-05-20,5,2023,0,740.388634
1,0,1,completed,4327,257.803148,2023-05-20,5,2023,0,740.388634
2,0,2,completed,3869,103.442092,2023-05-20,5,2023,0,740.388634
3,0,3,completed,7393,172.054542,2023-05-20,5,2023,0,740.388634
4,0,4,completed,8589,97.363922,2023-05-20,5,2023,0,740.388634
5,0,5,completed,7958,86.690624,2023-05-20,5,2023,0,740.388634
6,1,0,shipped,2911,10.241172,2023-07-02,7,2023,0,594.843751

# **Exercise 1.2**

##  _Familiarize yourself with the data in each of the tables. Do you understand what each column represent?_

## _Try to answer_:


### 1.   What does a row represent in `'sales_data'`?
### 2.   What does a row represent in `'customer_data'`?
### 3.   What does a row represent in `'product_data'`?
### 4.   Which column in `'sales_data'` relates an order to a row in `'customer_data'`?
### 5.   Which column in `'sales_data'` relates an order to a row in `'product_data'`?

In [ ]:
# SOLUTION BY RASMUS

# 1. - A row represents an item in an order.
# 2. - A row represents a customer
# 3. - A row represents a product for sale
# 4. - 'customer_id'
# 5. - 'item_id'

# **Exercise 1.3**

##  _Write a SELECT query that returns the order with the highest total. Return the full order (with all columns) and save as a variable. Print the result to cell output._

Hint: =MAX

In [ ]:
# SOLUTION BY RASMUS

order_max = conn.execute('SELECT * FROM sales_data WHERE order_total = MAX(order_total)').collect().to_pandas()
order_max

,order_id,order_sub_id,status,item_id,item_price,order_date,month_id,year_id,customer_id,order_total
0,241321,0,completed,1547,172.518854,2019-05-17,5,2019,48370,1442.841101
1,241321,1,completed,9165,89.526229,2019-05-17,5,2019,48370,1442.841101
2,241321,2,completed,4041,198.181084,2019-05-17,5,2019,48370,1442.841101
3,241321,3,completed,8957,352.306634,2019-05-17,5,2019,48370,1442.841101
4,241321,4,completed,6266,388.214712,2019-05-17,5,2019,48370,1442.841101
5,241321,5,completed,8239,242.093588,2019-05-17,5,2019,48370,1442.841101

# **Exercise 1.4**

##  _Use the data stored in the variable you created in 1.3 to write a SELECT query that returns all available information about the products that was sold in the order with the highest total. Print the results to cell output._

hint: IN

In [ ]:
# SOLUTION BY RASMUS

conn.execute(f'SELECT * FROM product_data WHERE item_id IN {str(tuple(order_max["item_id"]))}').collect().to_pandas()

,Product Name,Category,Product Specification,Shipping Weight,item_id,item_price
0,Anagram International A11362002 Oklahoma City ...,Toys & Games | Party Supplies | Balloons,ProductDimensions:18x0x18inches|ItemWeight:0.3...,0.32 ounces,1547,172.518854
1,Toy Story Scary Rex Woven Tapestry Throw Pillow,Home & Kitchen | Bedding | Kids' Bedding | Bla...,ProductDimensions:20x18x2inches|ItemWeight:1.5...,1.55 pounds,4041,198.181084
2,"Madame Alexander 8"" Tricks & Treats Wendy Toy,...",Toys & Games | Dolls & Accessories | Dolls,ProductDimensions:5.2x2.8x8.5inches|ItemWeight...,8.8 ounces,6266,388.214712
3,Rubie's Baby's Marvel Spider-Man Romper,"Clothing, Shoes & Jewelry | Costumes & Accesso...",None,3.04 ounces,8239,242.093588
4,"Petit Collage Magnetic Play Scene, Pet Hospita...",Toys & Games | Dress Up & Pretend Play | Prete...,ProductDimensions:9.2x7x1.2inches|ItemWeight:1...,1.1 pounds,8957,352.306634
5,Swing Set Stuff Inc. Commercial Polymer Belt S...,Toys & Games | Sports & Outdoor Play | Play Se...,ProductDimensions:12x8x12inches|ItemWeight:9po...,9.4 pounds,9165,89.526229

# **Exercise 1.5**

##  _Use the data stored in the variable you created in 1.3 to write a SELECT query that returns all available information about the customer that placed the order with the highest total. Print the results to cell output._

hint: =

In [ ]:
# SOLUTION BY RASMUS
conn.execute(f'SELECT * FROM customer_data WHERE customer_id = {str(order_max["customer_id"][0])}').collect().to_pandas()

,name,address,building,city,postcode,country_code,iban,swift,phone,registered,customer_id
0,Michelle Simpson,002 Jimmy Roads Suite 570,363,West Mark,69297,ZW,GB07AJIN12293863188268,CAYNGBDO,(358)278-1421x869,2016-03-14,48370

# **Exercise 2.1**

##  _Supposed we wanted to convert the parquet files to a single SQLite database, where each file becomes it's own table - just like in our pl.SQLContext:_

1. Which column in `'customer_data'` is an obvious candidate for a Primary Key?
2. Which column in `'product_data'` is an obvious candidate for a Primary Key?
3. Why should we construct an Index - not a Primary Key - on `'sales_data'` - and which column could be a potential candidate?

In [ ]:
# SOLUTION BY RASMUS

#1. - customer_id - it is a unique integer value
#2. - item_id - it is a unique integer value
#3. - order_id - it is not a unique integer value. One could also construct the index on (order_id, sub_order_id) - thats probabbly best


# **Exercise 2.2**
##_Download the two webshop SQLite database files `'webshop_data.db'` and `'webshop_data_no_indexing.db'`_ by running the cell below.

## We will use the function below to query the databases:

```
import sqlite3
# conn = sqlite3.connect(database_path)

def query_database(query, conn):
    return conn.execute(query).fetchall()
```

## and we define our query as the following

```
import numpy as np

customer_ids = np.random.randint(0, 9999, 10)
query = f'SELECT * FROM costumer_data WHERE customer_id IN {str(tuple(customer_ids))}'

```

## `customer_ids` will contain 10 random ids in the `customer_data` table, and the query asks for the corresponding rows.

## Establish a connection to each database, and use `%timeit -n 100 query_database(query = query, conn = your_connection)` to measure the execution time.

## Which of the two databases are faster for this query? Why?

In [ ]:
!gdown 1c66GNAYJxsYEfLNYgh53LtoA0ncnvnmd
!gdown 1CRZA2a_K3tkGQUo3C7Cdwi8x-sf-2UeE

Downloading...
From: https://drive.google.com/uc?id=1c66GNAYJxsYEfLNYgh53LtoA0ncnvnmd
To: /content/webshop_data_no_indexing.db
100% 263M/263M [00:03<00:00, 70.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1CRZA2a_K3tkGQUo3C7Cdwi8x-sf-2UeE
To: /content/webshop_data.db
100% 245M/245M [00:02<00:00, 88.6MB/s]

In [ ]:
# SOLUTION BY RASMUS

import numpy as np
customer_ids = np.random.randint(0, 9999, 10)
query = f'SELECT * from customer_data where customer_id in {str(tuple(customer_ids))}'
%timeit -n 100 query_database(query = query, conn = sqlite3.connect('/content/webshop_data.db'));
%timeit -n 100 query_database(query = query, conn = sqlite3.connect('/content/webshop_data_no_indexing.db'));

# first database is faster becaused it has customer_id as a primary key

247 µs ± 42.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
23.8 ms ± 4.73 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

# **Exercise 2.3**
##_Execute the same query as in 2.2 but using the pl.SQLContext from polars on the parquet-version of the dataset. How does the execution time compare to the databases above?_

In [ ]:
#SOLUTION BY RASMUS
%timeit -n 100 conn.execute(query).collect();
# similar in speed to the database without index.

20.3 ms ± 5.01 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

# **Bonus Exercises**

##  **a)** _Write memory efficient queries that answers the following questions:_



1.   _In what year did the webshop earn the most money?_
2.   _What is the average earnings in August? (average over years)_
3.   _Which product has been sold the most?_
4.   _Which customer has spent the most money at the webshop?_
5.   _Has all products been sold at least once?_

hint: DISTINCT, GROUP BY, SUM, NOT IN

## **b)** _Write a single SELECT query that returns the name of the customer that placed the order with the highest total. You may not use data stored in previous variables._
hint: LEFT JOIN

In [ ]:
# SOLUTION BY RASMUS
import pandas as pd
#A) 1.
conn.execute(f'SELECT DISTINCT year_id, SUM(item_price) as total FROM sales_data GROUP BY year_id').collect().to_pandas().max()['year_id']

2023.0

In [ ]:
#A)  2.
conn.execute(f'SELECT year_id, SUM(item_price) as total FROM sales_data WHERE month_id = 08 GROUP BY year_id').collect().to_pandas().mean()['total']

2387580.7168904133

In [ ]:
#A)  3.
count_per_product = conn.execute(f'SELECT item_id, COUNT(item_id) as n_times_sold FROM sales_data GROUP BY item_id').collect().to_pandas()
count_per_product.loc[count_per_product['n_times_sold'].idxmax(),:]

item_id         5038
n_times_sold     359
Name: 3783, dtype: int64

In [ ]:
#A)  4.
spending_per_costumer = conn.execute(f'SELECT customer_id, SUM(item_price) AS total FROM sales_data GROUP BY customer_id').collect().to_pandas()
customer_id = spending_per_costumer.loc[spending_per_costumer['total'].idxmax(),:]['customer_id']
conn.execute(f'SELECT * FROM customer_data WHERE customer_id == {customer_id}').collect().to_pandas()

,name,address,building,city,postcode,country_code,iban,swift,phone,registered,customer_id
0,Tyler Johnston,93610 Ashley Pike,7210,Daviston,94634,DK,GB91UOPE23298670257867,WILIGBSE0H6,919-235-6325x8503,2018-10-10,38359

In [ ]:
#A) 5.
# Returns a list of item_id's that has not been sold. Empty means all has been sold at least once :-)
conn.execute(f'SELECT item_id FROM product_data WHERE item_id NOT IN (SELECT DISTINCT item_id FROM sales_data)').collect().to_pandas()

Empty DataFrame
Columns: [item_id]
Index: []

In [ ]:
# SOLUTION BY RASMUS
# B)
conn.execute(f'SELECT name FROM customer_data LEFT JOIN sales_data ON customer_data.customer_id = sales_data.customer_id WHERE sales_data.order_total = MAX(sales_data.order_total) LIMIT 1').collect().to_pandas()

               name
0  Michelle Simpson